# 阶段一：安装依赖
FROM gradle:8.5.0-jdk<%= javaVersion %> as dependencies

WORKDIR /app

COPY build.gradle /app/build.gradle

# 只安装依赖，跳过测试
RUN gradle -v && gradle dependencies --no-daemon

# 阶段二：构建阶段
FROM dependencies as builder

COPY . /app

# 构建
RUN gradle clean build --no-daemon

# 阶段三：生产阶段
FROM eclipse-temurin:<%= javaVersion %>-jre-alpine

WORKDIR /app

COPY --from=builder /app/build/libs/main.jar /app

EXPOSE 8080

CMD ["java", "-jar", "main.jar"]
